### ISSUE TITLE
Failed to load arrows.app

### ISSUE THREAD

**Issue by CraigDeverall** [neo4j-labs/arrows.app#113]
index-2343261e.js:75 Uncaught Error: Minified Redux error #0; visit https://redux.js.org/Errors?code=0 for the full message or use the non-minified dev environment for full errors.
at qO (index-2343261e.js:75:3010)
at index-2343261e.js:185:37909
at index-2343261e.js:1:23
at index-2343261e.js:185:38246

Understand this error
cc.js?renew=false&referer=arrows-app-295615.nw.r.appspot.com&dnt=false&init=false:1 

Error: The domain ARROWS-APP-295615.NW.R.APPSPOT.COM is not authorized to show the cookie banner for domain group ID 0c2ea320-7217-4e6b-91f2-77765fc83255. Please add it to the domain group in the Cookiebot Manager to authorize the domain.

**Comment by kovcic** [comment]
@CraigDeverall if you have an error in Chrome, try disabling Redux extension. I had the same issue, but it's working with Redux extension disabled.

**Comment by saliez** [comment]
Ok with chromium but not with Firefox !

**Comment by cramatt** [comment]
I have the same issue. I needed to open a private window to get it working. I did not try disabling the redux extension, but I suspect it would be the same resolution.

**Comment by dejavu1987** [comment]
Thanks, I was panicked :D

**Comment by jexp** [comment]
I think, I fixed it, should work again: https://arrows.app
