### ISSUE TITLE
[ Error ] Download / Export to JSON- The string to be encoded contains characters outside of the Latin1 range

### ISSUE THREAD

**Issue by slavo3** [neo4j-labs/arrows.app#12]
Hi, app is cool! But there is some problem with exporting a graph using JSON when using latin characters.

Below simple correct example (export to json is executable)
CREATE (:Person)-[:_RELATED]->(:Car {name: "Its test name "})

**But when i would like to use some latin characters like**:
CREATE (:Person)-[:_RELATED]->(:Car {name: "Its test name with latin characters like śćżół"})
Export to Json causes an error:

react-dom.production.min.js:5058 DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Go (https://arrows.app/static/js/main.1d05466c.chunk.js:1:204237)
    at n.value (https://arrows.app/static/js/main.1d05466c.chunk.js:1:204871)
    at zo (https://arrows.app/static/js/2.057663d8.chunk.js:1:231891)
    at Lo (https://arrows.app/static/js/2.057663d8.chunk.js:1:231684)
    at gi (https://arrows.app/static/js/2.057663d8.chunk.js:1:267718)
    at ga (https://arrows.app/static/js/2.057663d8.chunk.js:1:259041)
    at ma (https://arrows.app/static/js/2.057663d8.chunk.js:1:258966)
    at sa (https://arrows.app/static/js/2.057663d8.chunk.js:1:255968)
    at https://arrows.app/static/js/2.057663d8.chunk.js:1:207158
    at e.unstable_runWithPriority (https://arrows.app/static/js/2.057663d8.chunk.js:1:282828)

**Comment by apcj** [comment]
Hi @slavo3 glad you like the app and thanks for reporting. This should now be fixed. Please make sure you hard refresh or clear your cache to get the latest code.
